name: slang-publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - "nomic"

permissions:
  id-token: write # Required for trusted publishing
  contents: read

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - run: "./bin/npm run slang:setup"
      - run: "./bin/npm run slang:build"
      - run: "./bin/npm publish"
